search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('artist_list/<int:artist_id>', views.artist_list, name='artist_list'),
    path('genre/', views.genre, name='genre'),
    path('chart/', views.chart, name='chart'),
]

team/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name='door.html'), name='home'),
    path('admin/', admin.site.urls),
    url('first/', TemplateView.as_view(template_name='first.html'), name='home1'),
    url('second/', TemplateView.as_view(template_name='second.html'), name='home2'),
    url('third/', TemplateView.as_view(template_name='third.html'), name='home3'),
    path('analy/', include('analy.urls')),
    path('search/', include('search.urls')),
    path('interest/', include('interest.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/models.py
from django.db import models

# Create your models here.

class Keywords(models.Model):
    song = models.CharField('제목', max_length=50)
    album = models.CharField('앨범', max_length=50)
    artist = models.CharField('가수', max_length=20)
    image = models.CharField('포스터', max_length=20)
    lyrics = models.TextField('가사', max_length=5000)
    release = models.CharField('발매날짜', max_length=10)
    genre = models.CharField('장르', max_length=20)

    def __str__(self):
        return self.song

class Artists(models.Model):
    artist = models.CharField('아티스트', max_length=20)
    image = models.CharField('포스터', max_length=20)
    artist_id = models.IntegerField('아티스트번호')

    def __str__(self):
        return self.artist

class Theme(models.Model):
    song = models.CharField('제목', max_length=50)
    album = models.CharField('앨범', max_length=50)
    artist = models.CharField('가수', max_length=20)
    lyrics = models.TextField('가사', max_length=5000)
    release = models.CharField('발매날짜', max_length=10)
    genre = models.CharField('장르', max_length=20)
    type = models.CharField('테마', max_length=10)

    def __str__(self):
        return self.type


class Chart(models.Model):
    song = models.CharField('제목', max_length=50)
    artist = models.CharField('가수', max_length=20)
    release = models.CharField('발매날짜', max_length=10)
    genre = models.CharField('장르', max_length=10)

    def __str__(self):
        return self.genre


class Name(models.Model):
    number = models.CharField('번호', max_length=10)
    name = models.CharField('장르', max_length=20)

    def __str__(self):
        return self.name

search/forms.py
from django import forms

search/views.py
from django.shortcuts import render, redirect
from search.models import Keywords, Theme, Chart, Name, Artists
import json
from urllib.parse import urlparse, parse_qsl, urlencode, urlunparse
from urllib.request import urlopen
import datetime
import time as mod_time


# Create your views here.


'''
하나의 함수에 다 넣으면 구분하기 힘들어서 카테고리에 따라 각각 수행하도록 했음.
'''

def search(request):
    if request.method == 'POST' and request.POST['item'] in ('keyword', 'lyrics'):
        return keyword(request)

    elif request.method == 'POST' and request.POST['item'] == 'artist':
        return artist(request)

    elif request.method == 'POST' and request.POST['item'] in ('movie', 'drama', 'musical'):
        return theme(request)

    else:
        return redirect('home2')


'''
각각의 노래마다 id가 존재하고, 그 id로 상세정보를 불러오는 방식은 동일하기 때문에 
하나의 함수에서 작업하도록 했음.
'''

def detail(id_num):
    id = id_num

    if id:
        urls = str(
            'https://www.music-flo.com/api/meta/v1/track/' + str(id))
        parts_d = urlparse(urls)
        qs_d = dict(parse_qsl(parts_d.query))
        today = datetime.datetime.now()
        today_time = int((mod_time.mktime(today.timetuple())))
        today_unixtime = (today_time * 1000)
        qs_d['timestamp'] = today_unixtime
        parts_d = parts_d._replace(query=urlencode(qs_d))
        new_url_d = urlunparse(parts_d)

        u_d = urlopen(new_url_d)
        data_d = u_d.read()
        j_d = json.loads(data_d)

        if 'data' in j_d.keys():
            obj_d = j_d['data']

            lyrics = obj_d['lyrics'] if 'lyrics' in obj_d.keys() else '가사정보가 없습니다.'
            try:
                release = datetime.datetime.strptime(obj_d['album']['releaseYmd'], '%Y%m%d').strftime(
                    '%Y.%m.%d') if ('album' in obj_d.keys()) and (
                        'releaseYmd' in obj_d['album'].keys()) else '앨범 발매연도를 알 수 없습니다.'
            except:
                release = obj_d['album']['releaseYmd']
            genre = obj_d['album']['genreStyle'] if ('album' in obj_d.keys()) and (
                    'genreStyle' in obj_d['album'].keys()) else '장르정보가 없습니다.'

        else:
            lyrics = '가사정보가 없습니다.'
            release = '앨범 발매연도를 알 수 없습니다.'
            genre = '장르정보가 없습니다.'

    else:
        lyrics = '가사정보가 없습니다.'
        release = '앨범 발매연도를 알 수 없습니다.'
        genre = '장르정보가 없습니다.'

    return lyrics, release, genre


'''
키워드 또는 가사로 검색할 때는 searchType만 다르고 데이터 형식이 동일해서 같이 수행하도록 했음.
'''
def keyword(request):
    if request.method == 'POST':
        Keywords.objects.all().delete()

        type = 'TRACK' if request.POST['item'] == 'keyword' else 'LYRICS'

        parts = urlparse(
            'https://www.music-flo.com/api/search/v2/search?searchType=TRACK&sortType=ACCURACY&size=100&page=1')
        qs = dict(parse_qsl(parts.query))
        qs['keyword'] = request.POST['name']
        qs['searchType'] = type
        today = datetime.datetime.now()
        today_time = int((mod_time.mktime(today.timetuple())))
        today_unixtime = (today_time * 1000)
        qs['timestamp'] = today_unixtime
        parts = parts._replace(query=urlencode(qs))
        new_url = urlunparse(parts)

        u = urlopen(new_url)

        data = u.read()
        j = json.loads(data)

        if ('data' in j.keys()) and ('list' in j['data'].keys()) and (len(j['data']['list']) > 0) and (
                'list' in j['data']['list'][0].keys()):

            obj = j['data']['list'][0]['list']

            for i in range(min(len(obj), 100)):
                song = obj[i]['name'] if 'name' in obj[i].keys() else '노래 제목을 알 수 없습니다.'
                album = obj[i]['album']['title'] if ('album' in obj[i].keys()) and (
                        'title' in obj[i]['album'].keys()) else '앨범명을 알 수 없습니다.'
                artist = obj[i]['representationArtist']['name'] if ('representationArtist' in obj[i].keys()) and (
                        'name' in obj[i]['representationArtist'].keys()) else '아티스트를 알 수 없습니다.'
                id = obj[i]['id'] if 'id' in obj[i].keys() else ''
                try:
                    image = obj[i]['album']['imgList'][0]['url']
                except:
                    image = '/static/img/noimg.jpg'

                lyrics, release, genre = detail(id)

                tmp = Keywords(song=song, album=album, artist=artist, lyrics=lyrics, release=release, genre=genre,
                               image=image)
                tmp.save()

        else:
            song = '노래 제목을 알 수 없습니다.'
            album = '앨범명을 알 수 없습니다.'
            artist = '아티스트를 알 수 없습니다.'
            image = '/static/img/noimg.jpg'
            id = ''
            lyrics, release, genre = detail(id)
            tmp = Keywords(song=song, album=album, artist=artist, lyrics=lyrics, release=release, genre=genre,
                           image=image)
            tmp.save()

        contents = Keywords.objects.all()

        return render(request, 'keyword.html', {'keyword': request.POST['name'], 'contents': contents})

    else:

        return redirect('home2')




'''
가수로 검색할 때는 마찬가지로 searchType만 다르지만, 데이터 형식이 다르고, 보여줘야 하는 화면도 달라서 
따로 수행하도록 했음. 먼저, 검색한 키워드에 해당하는 가수를 검색해서 어떤 가수가 있는지 보여준다.
그래서 따로 가수 목록만 저장하는 테이블 Artists를 만들어줬음.
'''
def artist(request):
    if request.method == 'POST':
        Artists.objects.all().delete()

        parts = urlparse(
            'https://www.music-flo.com/api/search/v2/search?searchType=ARTIST&sortType=ACCURACY&size=10&page=1')
        qs = dict(parse_qsl(parts.query))
        qs['keyword'] = request.POST['name']
        today = datetime.datetime.now()
        today_time = int((mod_time.mktime(today.timetuple())))
        today_unixtime = (today_time * 1000)
        qs['timestamp'] = today_unixtime
        parts = parts._replace(query=urlencode(qs))
        new_url = urlunparse(parts)

        u = urlopen(new_url)

        data = u.read()
        j = json.loads(data)

        if ('data' in j.keys()) and ('list' in j['data'].keys()) and (len(j['data']['list']) > 0) and (
                'list' in j['data']['list'][0].keys()):

            obj = j['data']['list'][0]['list']

            for i in range(min(len(obj), 10)):
                try:
                    image = obj[i]['imgList'][0]['url']
                except:
                    image = '/static/img/noimg.jpg'
                artist = obj[i]['name'] if 'name' in obj[i].keys() else '아티스트를 알 수 없습니다.'
                artist_id = obj[i]['id'] if 'id' in obj[i].keys() else ''

                tmp = Artists(image=image, artist=artist, artist_id=artist_id)
                tmp.save()

        else:
            image = '/static/img/noimg.jpg'
            artist = '아티스트를 알 수 없습니다.'
            artist_id = ''
            tmp = Artists(image=image, artist=artist, artist_id=artist_id)
            tmp.save()

        return render(request, 'artists.html', {'lists': Artists.objects.all(), 'keyword': request.POST['name']})

    else:
        return redirect('home2')


'''
내가 찾던 가수를 선택하면 그 때 그 가수의 곡 정보들을 크롤링한다.
결과를 보여주는 화면은 keyword와 동일하다.
'''
def artist_list(request, artist_id):
    if request.method == 'POST':
        Keywords.objects.all().delete()

        parts = urlparse(
            'https://www.music-flo.com/api/meta/v1/artist/' + str(artist_id) +
            '/track?sortType=POPULARITY&page=1&size=100&roleType=ALL')
        qs = dict(parse_qsl(parts.query))
        today = datetime.datetime.now()
        today_time = int((mod_time.mktime(today.timetuple())))
        today_unixtime = (today_time * 1000)
        qs['timestamp'] = today_unixtime
        parts = parts._replace(query=urlencode(qs))
        new_url = urlunparse(parts)

        u = urlopen(new_url)

        data = u.read()
        j = json.loads(data)

        if ('data' in j.keys()) and ('list' in j['data'].keys()):

            obj = j['data']['list']

            for i in range(min(len(obj), 100)):
                song = obj[i]['name'] if 'name' in obj[i].keys() else '노래 제목을 알 수 없습니다.'
                album = obj[i]['album']['title'] if ('album' in obj[i].keys()) and (
                        'title' in obj[i]['album'].keys()) else '앨범명을 알 수 없습니다.'
                artist = obj[i]['representationArtist']['name'] if ('representationArtist' in obj[i].keys()) and (
                        'name' in obj[i]['representationArtist'].keys()) else '아티스트를 알 수 없습니다.'
                id = obj[i]['id'] if 'id' in obj[i].keys() else ''
                try:
                    image = obj[i]['album']['imgList'][0]['url']
                except:
                    image = '/static/img/noimg.jpg'

                lyrics, release, genre = detail(id)

                tmp = Keywords(song=song, album=album, artist=artist, lyrics=lyrics, release=release, genre=genre,
                               image=image)
                tmp.save()

        else:
            song, album, artist = '노래 제목을 알 수 없습니다.', '앨범명을 알 수 없습니다.', '아티스트를 알 수 없습니다.'
            image = '/static/img/noimg.jpg'
            lyrics, release, genre = detail('')

            tmp = Keywords(song=song, album=album, artist=artist, lyrics=lyrics, release=release, genre=genre,
                           image=image)
            tmp.save()

        contents = Keywords.objects.all()

        return render(request, 'keyword.html',
                      {'contents': contents, 'keyword': Artists.objects.get(artist_id=artist_id).artist})

    else:
        return redirect('home2')




def theme(request):
    if request.method == 'POST':

        if request.POST['item'] == 'movie':
            name = request.POST['name']
            type = 'movie'

        elif request.POST['item'] == 'drama':
            name = request.POST['name']
            type = 'drama'

        elif request.POST['item'] == 'musical':
            name = request.POST['name']
            type = 'musical'

        Theme.objects.filter(type=type).delete()

        # 1. 앨범 목록에서 검색.
        parts = urlparse(

search/templates/artists.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}

<style>
    body{
            background:linear-gradient(0deg,rgba(0, 0, 0, 0.35),rgba(0, 0, 0, 0.35)),url("/static/img/backgroundimg_6.jpg");
            background-size: cover !important;
            background-repeat: no-repeat !important;
            background-position: center !important;
            margin: 0px;
        }
    a{
      text-decoration:none;
    }

    .item-list:hover{
        background-color:rgba(93,93,93,0.6);
    }

    .item-list{
        color : #3d3d3d;
        position: relative;
        cursor: pointer;
        display: block;
        overflow: hidden;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        -webkit-tap-highlight-color: transparent;
        vertical-align: middle;
        z-index: 1;
        transition: .3s ease-out;
    }

    .modal-window {
      position: fixed;
      background-color: rgba(1, 1, 1, 0.15);
      top: -130px;
      right: 0;
      bottom: 0;
      left: 0;
      z-index: 999;
      opacity: 0;
      pointer-events: none;
      -webkit-transition: all 0.3s;
      -moz-transition: all 0.3s;
      transition: all 0.3s;
    }

    .modal-window:target {
      opacity: 1;
      pointer-events: auto;
    }

    .modal-window>div {
      width: 400px;
      position: relative;
      margin: 10% auto;
      padding: 2rem;
      background: #f3f3f3;
      color: #444;
    }

    .modal-window header {
      font-weight: bold;
    }

    .modal-close {
      color: #aaa;
      line-height: 50px;
      font-size: 100%;
      position: absolute;
      right: 0;
      text-align: center;
      top: 0;
      width: 70px;
      text-decoration: none;
    }

    .modal-close:hover {
      color: #000;
    }

    .modal-window h1 {
      font-size: 150%;
      margin: 0 0 15px;
    }

    .btn, .btn-large, .btn-flat {
        border: none;
        border-radius: 2px;
        display: inline-block;
        height: 36px;
        line-height: 36px;
        padding: .005em .5em 1em;
        text-transform: uppercase;
        vertical-align: middle;
        -webkit-tap-highlight-color: transparent;
    }

    .btn, .btn-large {
        text-decoration: none;
        color: #fff;
        background-color: #26a69a;
        text-align: center;
        letter-spacing: .5px;
        transition: .2s ease-out;
        cursor: pointer;
    }

    ghpages-materialize.css:1
    .btn, .btn-large, .btn-floating, .btn-large, .btn-flat {
        font-size: 0.6rem;
        outline: 0;
    }

    #popup-content {
      height: 100%;
      overflow: scroll;
    }

    th, td {
    text-align: center;
    font-size: 15px;
    }

    p {
    font-size: 115%;
    }
    h2 {
    color: #FFFFF0;
    opacity: 0.8;
    }
    .modal-window::-webkit-scrollbar {
    display: none;
    }

</style>

<h2 class="mb-4">{{ keyword }}</h2>

<div class="container here">

    <table class="table table-hover keyword-table">

        <thead>
            <tr>
                <th scope="col" style="width: 5%">No.</th>
                <th scope="col" style="width: 10%">포스터</th>
                <th scope="col" style="width: 15%">가수</th>
                <th scope="col" style="width: 10%">상세정보</th>
            </tr>
        </thead>

        <tbody>
           {% for artist in lists %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <td>
                    <img src="{{ artist.image }}">
                </td>
                <td>{{ artist.artist }}</td>
                <td>
                    <form action="{% url 'search:artist_list' artist.artist_id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="submit" value="열기" class="item-list btn">
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

</div>

{% endblock %}

search/templates/chart.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}
<style>
    body{
            background:linear-gradient(0deg,rgba(0, 0, 0, 0.35),rgba(0, 0, 0, 0.35)),url("/static/img/backgroundimg_6.jpg");
            background-size: cover !important;
            background-repeat: no-repeat !important;
            background-position: center !important;
            margin: 0px;
        }
    a{
      text-decoration:none;
    }

    .item-list:hover{
        background-color:rgba(93,93,93,0.6);
    }

    .item-list{
      color : #3d3d3d;
        position: relative;
        cursor: pointer;
        display: block;
        overflow: hidden;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        -webkit-tap-highlight-color: transparent;
        vertical-align: middle;
        z-index: 1;
        transition: .3s ease-out;
    }

    .modal-window {
      position: fixed;
      background-color: rgba(1, 1, 1, 0.15);
      top: -130px;
      right: 0;
      bottom: 0;
      left: 0;
      z-index: 999;
      opacity: 0;
      pointer-events: none;
      -webkit-transition: all 0.3s;
      -moz-transition: all 0.3s;
      transition: all 0.3s;
    }

    .modal-window:target {
      opacity: 1;
      pointer-events: auto;
    }

    .modal-window>div {
      width: 400px;
      position: relative;
      margin: 10% auto;
      padding: 2rem;
      background: #f3f3f3;
      color: #444;
    }

    .modal-window header {
      font-weight: bold;
    }

    .modal-close {
      color: #aaa;
      line-height: 50px;
      font-size: 100%;
      position: absolute;
      right: 0;
      text-align: center;
      top: 0;
      width: 70px;
      text-decoration: none;
    }

    .modal-close:hover {
      color: #000;
    }

    .modal-window h1 {
      font-size: 150%;
      margin: 0 0 15px;
    }

    .btn, .btn-large, .btn-flat {
        border: none;
        border-radius: 2px;
        display: inline-block;
        height: 36px;
        line-height: 36px;
        padding: .005em .5em 1em;
        text-transform: uppercase;
        vertical-align: middle;
        -webkit-tap-highlight-color: transparent;
    }

    .btn, .btn-large {
        text-decoration: none;
        color: #fff;
        background-color: #26a69a;
        text-align: center;
        letter-spacing: .5px;
        transition: .2s ease-out;
        cursor: pointer;
    }

    ghpages-materialize.css:1
    .btn, .btn-large, .btn-floating, .btn-large, .btn-flat {
        font-size: 0.6rem;
        outline: 0;
    }

    #popup-content {
      height: 100%;
      overflow: scroll;
    }

    th, td {
    text-align: center;
    font-size: 15px;
    }

    p {
    font-size: 115%;
    }
    h2 {
    color: #FFFFF0;
    opacity: 0.8;
    }
    .modal-window::-webkit-scrollbar {
    display: none;
    }

</style>

<h2 class="mb-4">{{ keyword }}</h2>

<div class="container here">

    <table class="table table-hover keyword-table">

        <thead>
            <tr>
                <th scope="col" style="width: 5%">No.</th>
                <th scope="col" style="width: 30%">노래제목</th>
                <th scope="col" style="width: 35%">가수</th>
                <th scope="col" style="width: 20%">발매날짜</th>
            </tr>
        </thead>

        <tbody>
           {% for content in contents %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <td>{{ content.song }}</td>
                <td>{{ content.artist }}</td>
                <td>{{ content.release }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

</div>

{% endblock %}

search/templates/keyword.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}
<style>
    body{
            background:linear-gradient(0deg,rgba(0, 0, 0, 0.35),rgba(0, 0, 0, 0.35)),url("/static/img/backgroundimg_6.jpg");
            background-size: cover !important;
            background-repeat: no-repeat !important;
            background-position: center !important;
            margin: 0px;
        }
    a{
      text-decoration:none;
    }

    .item-list:hover{
        background-color:rgba(93,93,93,0.6);
    }

    .item-list{
      color : #3d3d3d;
        position: relative;
        cursor: pointer;
        display: block;
        overflow: hidden;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        -webkit-tap-highlight-color: transparent;
        vertical-align: middle;
        z-index: 1;
        transition: .3s ease-out;
    }

    .modal-window {
      position: fixed;
      background-color: rgba(1, 1, 1, 0.15);
      top: -130px;
      right: 0;
      bottom: 0;
      left: 0;
      z-index: 999;
      opacity: 0;
      pointer-events: none;
      -webkit-transition: all 0.3s;
      -moz-transition: all 0.3s;
      transition: all 0.3s;
    }

    .modal-window:target {
      opacity: 1;
      pointer-events: auto;
    }

    .modal-window>div {
      width: 400px;
      position: relative;
      margin: 10% auto;
      padding: 2rem;
      background: #f3f3f3;
      color: #444;
    }

    .modal-window header {
      font-weight: bold;
    }

    .modal-close {
      color: #aaa;
      line-height: 50px;
      font-size: 100%;
      position: absolute;
      right: 0;
      text-align: center;
      top: 0;
      width: 70px;
      text-decoration: none;
    }

    .modal-close:hover {
      color: #000;
    }

    .modal-window h1 {
      font-size: 150%;
      margin: 0 0 15px;
    }

    .btn, .btn-large, .btn-flat {
        border: none;
        border-radius: 2px;
        display: inline-block;
        height: 36px;
        line-height: 36px;
        padding: .005em .5em 1em;
        text-transform: uppercase;
        vertical-align: middle;
        -webkit-tap-highlight-color: transparent;
    }

    .btn, .btn-large {
        text-decoration: none;
        color: #fff;
        background-color: #26a69a;
        text-align: center;
        letter-spacing: .5px;
        transition: .2s ease-out;
        cursor: pointer;
    }

    ghpages-materialize.css:1
    .btn, .btn-large, .btn-floating, .btn-large, .btn-flat {
        font-size: 0.6rem;
        outline: 0;
    }

    #popup-content {
      height: 100%;
      overflow: scroll;
    }

    th, td {
    text-align: center;
    font-size: 15px;
    }

    p {
    font-size: 115%;
    }
    h2 {
    color: #FFFFF0;
    opacity: 0.8;
    }
    .modal-window::-webkit-scrollbar {
    display: none;
    }

</style>

<h2 class="mb-4">{{ keyword }}</h2>

<div class="container here">

    <table class="table table-hover keyword-table">

        <thead>
            <tr>
                <th scope="col" style="width: 5%">No.</th>
                <th scope="col" style="width: 10%">포스터</th>
                <th scope="col" style="width: 30%">노래제목</th>
                <th scope="col" style="width: 30%">앨범제목</th>
                <th scope="col" style="width: 15%">가수</th>
                <th scope="col" style="width: 10%">상세정보</th>
            </tr>
        </thead>

        <tbody>
           {% for content in contents %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <td>
                    <img src="{{ content.image }}">
                </td>
                <td>{{ content.song }}</td>
                <td>{{ content.album }}</td>
                <td>{{ content.artist }}</td>
                <td>
                    <a class="item-list btn" href="#open-moda-{{ forloop.counter }}" >열기</a>

                    <div id="open-moda-{{ forloop.counter }}" class="modal-window" style="overflow-X:hidden">
                        <div display="inline">
                            <a href="#modal-close" title="Close" class="modal-close">Close</a>
                            <p>제목: {{ content.song }}</p>
                            <p>장르: {{ content.genre }}</p>
                            <p>발매날짜: {{ content.release }}</p>
                            <p>가사:</p>
                            <pre>
                                <p>{{ content.lyrics }}</p>
                            </pre>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

</div>

{% endblock %}