analy/urls.py
from django.urls import path
from . import views

app_name = 'analy'
urlpatterns = [
    path('upload/', views.upload, name='upload'),
]

interest/urls.py
from django.urls import path
from . import views

app_name = 'interest'
urlpatterns = [
    path('interest/', views.interest, name='interest'),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('artist_list/<int:artist_id>', views.artist_list, name='artist_list'),
    path('genre/', views.genre, name='genre'),
    path('chart/', views.chart, name='chart'),
]

team/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name='door.html'), name='home'),
    path('admin/', admin.site.urls),
    url('first/', TemplateView.as_view(template_name='first.html'), name='home1'),
    url('second/', TemplateView.as_view(template_name='second.html'), name='home2'),
    url('third/', TemplateView.as_view(template_name='third.html'), name='home3'),
    path('analy/', include('analy.urls')),
    path('search/', include('search.urls')),
    path('interest/', include('interest.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <title>웹과 음악 사이</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <script
            src="https://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
            crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.4.0/wavesurfer.min.js"></script>
    <link rel="stylesheet" href="/static/css/animation.css">
    <link rel="stylesheet" href="/static/css/nav_text.css">


    <script src="/static/js/animation.js"></script>


    <style>
        .mydiv-top {
        height: 10px;
        }
        .door1 {
        height: 90px;
        text-align: center;
        vertical-align: middle;
        padding: 0.6em 0 0;
        }
        .keyword-table {
        opacity: 0.90;
        background-color: #FFFFF0;
        }
        .mytext {
        color: #FFFFF0;
        text-align: center;
        }
        .here {
        overflow-y:scroll;
        width:1050px;
        height:600px;
        }
        .here::-webkit-scrollbar {
        display: none;
        }
        nav {
        opacity: 0.8;
        }
        #sidebar {
        background-color: #212529;
        }

    </style>
</head>

<body id="bg">
    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar" >
                <div class="myNavText" style="text-align: center; height: 100px; padding-top: 15px; font-size: 25px;">
                    <a class="logo myNavText_1" href="{% url 'home' %}" style="color: #60a5f7; font-weight: bold;">웹과 음악 사이<span class="myNavText_span">&nbsp;</span></a>
                </div>
                <ul class="list-unstyled components mb-5" style="font-weight: bold ">
                    <li class="active" onmouseover="func1(1)">
                        <a href="{% url 'home1' %}"><span class="fa fa-upload mr-3"></span> 음악 분석</a>
                    </li>
                    <li class="active" onmouseover="func1(2)">
                        <a href="{% url 'home2' %}"><span class="fa fa-search mr-3"></span> 음악 검색</a>
                    </li>
                    <li class="active" onmouseover="func1(3)">
                        <a href="{% url 'search:genre' %}"><span class="fa fa-list mr-3"></span> 장르별 인기차트</a>
                    </li>
                    <li class="active" onmouseover="func1(4)">
                        <a href="{% url 'home3' %}"><span class="fa fa-headphones mr-3"></span> 인기차트 100</a>
                    </li>
                </ul>
        </nav>
        <div id="content" class="p-4 p-md-5 pt-5">
            <div class="mydiv-top"></div>
            {% block container %}
            {% endblock %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="/static/js/jquery.min.js" type="2e70319bb3298c022c929462-text/javascript"></script>
    <script src="/static/js/popper.js" type="2e70319bb3298c022c929462-text/javascript"></script>
    <script src="/static/js/bootstrap.min.js" type="2e70319bb3298c022c929462-text/javascript"></script>
    <script src="/static/js/main.js" type="2e70319bb3298c022c929462-text/javascript"></script>
    <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js"
            data-cf-settings="2e70319bb3298c022c929462-|49" defer=""></script>
</body>
</html>

team/templates/door.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js">
<link rel="stylesheet" href="/static/css/door.css">


<style>
    body{
        background:linear-gradient(0deg,rgba(0, 0, 0, 0.35),rgba(0, 0, 0, 0.35)),url("/static/img/back.jpg");
        background-size: cover !important;
    @@ -13,8 +27,82 @@
    #a-here {
        font-size: 20px;
    }

</style>

<body class="top-container-bg">

<div class="door" style="text-align: center; transform: translate(-30%, -30%);">
    <h2 style="color: white;">웹과 음악 사이</h2>
   <br>
    코로나19로 남보다는 나와 함께하는 시간이 많아지고,<br>
    마스크로 입과 코는 가려도 눈과 귀는 가리지 못 하니,<br>
    보고 듣는 즐거움의 소중함을 느껴 만들었습니다.<br>
    당신이 원하는 음악을 분석하고<br>
    당신이 원하는 음악을 찾아드립니다.<br>
</div>

<div class="mydiv-top"></div>

    <script src="/static/js/door.js"></script>

</body>
{% endblock %}

team/templates/first.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}




<style>
    body{
            background:linear-gradient(0deg,rgba(0, 0, 0, 0.35),rgba(0, 0, 0, 0.35)),url("/static/img/backgroundimg_1.jpg");
            background-size: cover !important;
            background-repeat: no-repeat !important;
            background-position: center !important;
            margin: 0px;
        }
</style>

<div style="transform: translate(0%, 100%);">

    <h2 class="mb-4 mytext">내 음악 분석하기</h2>
    <p style="text-align: center; color: #FFFFF0;">분석하고자 하는 음악파일을 업로드 해주세요. <br>
    ※파일 형식: .wav .mp3 .aac .ogg .wma .flac .alac .aiff .audio
    </p>

    <div style="text-align: center;">
        <form action="{% url 'analy:upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input  id="input-audio-file" type="file" name="audio"
                    accept=".wav,.mp3,.aac,.ogg,.wma,.flac,.alac,.aiff, .audio/*"
                    multiple="multiple" style="color: #FFFFF0;">
            <input type="submit" value="업로드">
        </form>
    </div>

</div>

{% endblock %}

team/templates/genre.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}

<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
<link href="/static/css/main.css" rel="stylesheet" />

<style>
    body{
            background:linear-gradient(0deg,rgba(0, 0, 0, 0.35),rgba(0, 0, 0, 0.35)),url("/static/img/backgroundimg_3.jpg");
            background-size: cover !important;
            background-repeat: no-repeat !important;
            background-position: center !important;
            margin: 0px;
        }
    .s003 form .inner-form .input-field.third-wrap .btn-search svg {
    width: 23px;
    }
</style>


<div style="transform: translate(0%, 70%);">

    <h2 class="mb-4 mytext">장르별 인기차트 검색</h2>
    <p style="text-align: center; color: #FFFFF0;">원하는 장르를 선택해주세요!</p>

    <div style="text-align: center;">

        <div class="container s003" style="min-height: 10px; width: 580px; background-color: rgba(102, 102, 102, 0.5);">
            <form action="{% url 'search:chart' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="inner-form" style="width: 550px;">
                <div class="input-field first-wrap" style="width: 100%;">
                    <div class="input-select" style="transform: translate(0%, 28%);">
                        <select data-trigger="" name="item">
                            {% for name in names %}
                            <option value="{{ name.number }}" >{{ name.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="input-field third-wrap">
                    <button class="btn-search" type="submit">
                        <svg class="svg-inline--fa fa-search fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="search" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                        </svg>
                    </button>
                </div>
            </div>
            </form>

        </div>

    </div>

</div>

<script src="/static/js/choices.js"></script>
<script>
  const choices = new Choices('[data-trigger]',
  {
    searchEnabled: false,
    itemSelectText: '',
  });

</script>

{% endblock %}

team/templates/second.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}

    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
    <link href="/static/css/main.css" rel="stylesheet" />

<style>
    body{
            background:linear-gradient(0deg,rgba(0, 0, 0, 0.35),rgba(0, 0, 0, 0.35)),url("/static/img/backgroundimg_2.jpg");
            background-size: cover !important;
            background-repeat: no-repeat !important;
            background-position: center !important;
            margin: 0px;
        }
    .s003 form .inner-form .input-field.third-wrap .btn-search svg {
    width: 23px;
    }
</style>


<div style="transform: translate(0%, 70%);">

    <h2 class="mb-4 mytext">키워드로 검색하기</h2>
    <p style="text-align: center; color: #FFFFF0;">※최대 100가지를 알려드리며, 네트워크 환경에 따라 시간이 소요될 수 있습니다.</p>

    <div style="text-align: center;">

        <div class="container s003" style="min-height: 10px; width: 70%; background-color: rgba(102, 102, 102, 0.5);">

            <form action="{% url 'search:search' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="inner-form">

                    <div class="input-field first-wrap">
                        <div class="input-select" style="transform: translate(0%, 28%);">
                            <select data-trigger="" name="item">
                                <option value="keyword" >키워드</option>
                                <option value="artist">아티스트</option>
                                <option value="lyrics">가사</option>
                                <option value="movie">영화 OST</option>
                                <option value="drama">드라마 OST</option>
                                <option value="musical">뮤지컬 OST</option>
                            </select>
                        </div>
                    </div>

                    <div class="input-field second-wrap">
                        <input id="search" type="text" placeholder="Enter Keywords?" name="name"/>
                    </div>

                    <div class="input-field third-wrap">
                        <button class="btn-search" type="submit">
                            <svg class="svg-inline--fa fa-search fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="search" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                            </svg>
                        </button>
                    </div>

                </div>

            </form>

        </div>

    </div>

</div>

<script src="/static/js/choices.js"></script>
<script>
  const choices = new Choices('[data-trigger]',
  {
    searchEnabled: false,
    itemSelectText: '',
  });

</script>

{% endblock %}

team/templates/third.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block container %}

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="author" content="colorlib.com">
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500" rel="stylesheet" />
<link href="/static/css/main_2.css" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
<link href="/static/css/main.css" rel="stylesheet" />


<style>
    body{
            background:linear-gradient(0deg,rgba(0, 0, 0, 0.35),rgba(0, 0, 0, 0.35)),url("/static/img/backgroundimg_4.jpg");
            background-size: cover !important;
            background-repeat: no-repeat !important;
            background-position: center !important;
            margin: 0px;
        }
</style>

<div class="container" style="transform: translate(0%, 150%);">
    <h2 class="mb-4 mytext">일일 인기차트 100</h2>
    <p style="text-align: center; color: #FFFFF0;">원하는 날짜를 선택해주세요!</p>
</div>


<div class="s002 s003 container" style="transform: translate(3%, 110%); width: 380px; background-color: rgba(102, 102, 102, 0.5);">

    <form action="{% url 'interest:interest' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="inner-form" style="width: 350px;">

            <div class="input-field second-wrap">
                <div class="icon-wrap" style="width: 20px;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M17 12h-5v5h5v-5zM16 1v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2h-1V1h-2zm3 18H5V8h14v11z"></path>
                    </svg>
                </div>
                <input class="datepicker" id="depart" type="date" placeholder="2020-01-01" name="date">
            </div>

            <div class="input-field third-wrap">
                <button class="btn-search" type="submit" style="width: 140px;">
                    <svg class="svg-inline--fa fa-search fa-w-16" aria-hidden="true" data-prefix="fas" data-icon="search" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                        <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                    </svg>
                </button>
            </div>
        </div>

    </form>

</div>

<script src="/static/js/choices_2.js" type="45557f3c792b0ce6d9c9de08-text/javascript"></script>
<script src="/static/js/flatpickr.js" type="45557f3c792b0ce6d9c9de08-text/javascript"></script>

<script type="45557f3c792b0ce6d9c9de08-text/javascript">
      flatpickr(".datepicker",
      {});
</script>

<script type="45557f3c792b0ce6d9c9de08-text/javascript">
      const choices = new Choices('[data-trigger]',
      {
        searchEnabled: false,
        itemSelectText: '',
      });

</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="45557f3c792b0ce6d9c9de08-text/javascript"></script>
<script type="45557f3c792b0ce6d9c9de08-text/javascript">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="45557f3c792b0ce6d9c9de08-|49" defer=""></script>

<script src="/static/js/choices.js"></script>

<script>
const choices = new Choices('[data-trigger]',
{
 searchEnabled: false,
 itemSelectText: '',
});
</script>


{% endblock %}